### PR TITLE
Sometimes the partition Bootable flag is set.

### PR DESCRIPTION
**Pull request by razorsedge**
Gracefully deal with column 2 being a '*'.

```
# echo p | fdisk "${ROOT_DEVICE}" 2>/dev/null

Command (m for help):
Disk /dev/xvda: 53.7 GB, 53687091200 bytes
255 heads, 63 sectors/track, 6527 cylinders
Units = cylinders of 16065 * 512 = 8225280 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x000571b3

    Device Boot      Start         End      Blocks   Id  System
/dev/xvda1   *           1        1045     8387584   83  Linux
```

### CODE REVIEW

**Comment by andreisavu** [comment]
Hi Mike - thanks for this patch. What base AMI have you used when you hit this limitation? How are you using Director?

**Comment by razorsedge** [comment]
ami-1255b321  centos.org CentOS 6

I am testing out both the server and client deployment methods.  Everything else about the CentOS deployments seems to work, except the root disk expansion.

**Comment by razorsedge** [comment]
Any update as to this PR?

**Comment by andreisavu** [comment]
We are making this change internally and it's going to be part of the next repository refresh.

**Comment by bhavanki** [comment]
Hi there,

It looks like the change here made it in back in May, along with some other improvements to the script.

Thank you so much for the fix!

**Pull request closed without merging**
